# Site settings
title: Zeni's Portfolio
description: Data Scientist & Analyst | BI Developer
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zheng(Zeni) Zhang
user_description: Aspiring Data Scientist with a growing expertise in data analysis and strong foundation in business intelligence. Experienced in developing statistical models and machine learning applications, with a focus on business insights. Enthusiastic about creating impactful visualizations and implementing analytical solutions to derive business value from data.
user_title: Data Scientist & Analyst | BI Developer
email: zhangzz1218@gmail.com
github_username:  zhangz128
linkedin_username: zhangz128

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
