# Site settings
title: Zeni's Portfolio
description: Data Scientist & Analyst | BI Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhangz128.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zheng(Zeni) Zhang
user_description: Hello! I'm a data enthusiast looking to start my career as a Data Analyst where I can apply my machine learning skills to solve real business problems. I've gained practical experience working with various data tools like SQL, Tableau, and Power BI through internships where I created dashboards, automated reporting, and improved data quality. I enjoy turning raw data into insights that help businesses make better decisions and am excited to bring my analytical mindset to a team where I can continue learning and growing.
user_title: Data Scientist & Analyst | BI Developer
email: zhangzz1218@gmail.com
github_username:  zhangz128
linkedin_username: zhangz128

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
